[package]
name = "lumi"
version.workspace = true
edition.workspace = true
license.workspace = true
description = ""

[dependencies]
tokio = { workspace = true }
lumi_server = { workspace = true }

[[bin]]
name = "lumi"
path = "src/main.rs"