[package]
name = "lumi"
version = "2.0.0+rc1"
edition = "2024"

[dependencies]
axum = "0.8.7"
clap = { version = "4.5.53", features = ["derive"] }
lazy_static = "1.5.0"
quick-xml = { version = "0.38.4", features = ["serialize"]}
serde = { version = "1.0.228", features = ["derive"]}
tokio = { version = "1.48.0", features = ["full"] }
