[package]
name = "lumi_credentials"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
rand = { workspace = true }
axum = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
hex =  { workspace = true }